import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lexend_Exa } from 'next/font/google'
import { Lexend_Zetta } from 'next/font/google'


import "./globals.css";

const lexendExa = Lexend_Exa({ 
  subsets: ['latin'],
  variable: '--font-lexend-exa'
})

const lexendZetta = Lexend_Zetta({ 
  subsets: ['latin'],
  variable: '--font-lexend-zetta'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendExa.className} ${lexendZetta.variable}`}>
        {children}
      </body>
    </html>
  );
}
